version: '2'

services:
  portus:
    build: .
    image: opensuse/portus:development
    command: bundle exec rails runner /srv/Portus/examples/development/compose/init.rb
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=registry.monapi.com
      - PORTUS_PUMA_HOST=0.0.0.0:3000
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false

      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=Bu@da@2212
      - PORTUS_DB_POOL=5

      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/srv/Portus

  background:
    image: opensuse/portus:development
    entrypoint: bundle exec rails runner /srv/Portus/bin/background.rb
    depends_on:
      - portus
      - db
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=registry.monapi.com

      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS

      - PORTUS_DB_HOST=db
      - PORTUS_DB_PASSWORD=Bu@da@2212
      - PORTUS_DB_POOL=5
    volumes:
      - .:/srv/Portus
    links:
      - db

  webpack:
    image: kkarczmarczyk/node-yarn:6.9-slim
    command: bash /srv/Portus/examples/development/compose/bootstrap-webpack
    working_dir: /srv/Portus
    volumes:
      - .:/srv/Portus

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: Bu@da@2212
    volumes:
      - /registry_data/mysql_portus/data:/var/lib/mysql

  postgres:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: portus
    volumes:
      - /registry_data/postgresql_portus/data:/var/lib/postgresql/data

  registry:
    image: library/registry:2.6
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry_data
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_DEBUG_ADDR: 0.0.0.0:5001

      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /etc/docker/registry/portus.crt

      REGISTRY_AUTH_TOKEN_REALM: http://registry.monapi.com:3000/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: registry.monapi.com:5000
      REGISTRY_AUTH_TOKEN_ISSUER: registry.monapi.com

      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://registry.monapi.com:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /registry_data/portus:/registry_data
      - ./examples/development/compose/portus.crt:/etc/docker/registry/portus.crt:ro
    ports:
      - 5000:5000
      - 5001:5001
    links:
      - portus